apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: taeyoungk/ddackdae-backend:0.6.0
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Asia/Seoul"
      restartPolicy: Always
