apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80              # 클러스터 내부에서 서비스 접근용 포트
      targetPort: 8080      # 백엔드 컨테이너가 실제로 사용하는 포트
      nodePort: 30081       # 외부에서 접근할 NodePort (30000~32767 중 아무거나 지정 가능, 안주면 자동 할당됨)
